[package]
name = "orma"
version = "0.1.0"
edition = "2024"
description = "Loads a stateless system's passwords and keys at boot from a separate volume"
license = "GPL-3.0-or-later"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[dependencies]
argh = "0.1"
libc = "0.2"
rpassword = "7"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"
